/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.19 from the
 * contents of Kill.xs. Do not edit this file, edit Kill.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "Kill.xs"
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"
#include "main.c"

#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#line 20 "Kill.c"

XS(XS_Win32__Process__Kill_pTerminate); /* prototype to pass -Wmissing-prototypes */
XS(XS_Win32__Process__Kill_pTerminate)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Win32::Process::Kill::pTerminate", "ProcessId");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	int	RETVAL;
	dXSTARG;
	int	ProcessId = (int)SvIV(ST(0));

	RETVAL = pTerminate(ProcessId);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Win32__Process__Kill_AdjustPrivileges); /* prototype to pass -Wmissing-prototypes */
XS(XS_Win32__Process__Kill_AdjustPrivileges)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Win32::Process::Kill::AdjustPrivileges", "iPName");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	int	RETVAL;
	dXSTARG;
	int	iPName = (int)SvIV(ST(0));

	RETVAL = AdjustPrivileges(iPName);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Win32__Process__Kill); /* prototype to pass -Wmissing-prototypes */
XS(boot_Win32__Process__Kill)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    char* file = __FILE__;

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

        newXS("Win32::Process::Kill::pTerminate", XS_Win32__Process__Kill_pTerminate, file);
        newXS("Win32::Process::Kill::AdjustPrivileges", XS_Win32__Process__Kill_AdjustPrivileges, file);
    if (PL_unitcheckav)
         call_list(PL_scopestack_ix, PL_unitcheckav);
    XSRETURN_YES;
}

